services:
  # MySQL Service
  db:
    image: mysql:latest
    container_name: geoprofs-lars-db
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: geoprofs_lars_db
      MYSQL_USER: geoprofs_lars_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  # Laravel/PHP Service
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: geoprofs-lars-backend
    ports:
      - "8080:8000"
    volumes:
      - ./src/backend:/var/www/html
    depends_on:
      - db
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
